version: '3.8'

services:
  db:
    image: postgres:15
    container_name: starinc-postgres
    environment:
      POSTGRES_USER: starinc_user
      POSTGRES_PASSWORD: starinc_password
      POSTGRES_DB: starinc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
